### ISSUE TITLE
importing importRosBag

### ISSUE THREAD

**Issue by Iaxama** [event-driven-robotics/bimvee#1]
When importing importRosBag i have to type:
 from bimvee.importRosbag.importRosbag.importRosbag import importRosbag
which looks ugly

Maybe moving the submodule one level above would make it look nicer :D

**Comment by simbamford** [comment]
I will move this. 
However:
a) You'll still have to type:
from importRosbag.importRosbag import importRosbag
b) Why are you importing it anyway? You should import importRpgDvsRos, or possibly importAe.

**Comment by simbamford** [comment]
Actually, no, it's better not to move it, because at the moment the code level only has to refer to itself. inside importRogDvsRos it says:

from .importRosbag.importRosbag.importRosbag import importRosbag
    
If I do what you say I'll have to ascend the relative path before getting to the code I need to import.
